Update configure

diff --git a/GUI/configure b/GUI/configure
--- a/GUI/configure
+++ b/GUI/configure
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/bash
 
 cp -r sites/ $HOME/
 touch $HOME/sites/log.txt
@@ -6,6 +6,44 @@ touch $HOME/sites/.history.txt
 touch $HOME/sites/.link.txt
 chmod u+x phishing-gui.py
 
-sudo apt-get install python3-pip -y
-pip3 install -r requirements.txt
 
+echo -e "${yellow}[*]${white} Cheking Ngrok.."
+    if [[ -e ngrok ]];then
+        sleep 1 
+        echo -e "${green}[+]${white} Ngrok Found.."
+    else
+        echo -e "${yellow}[+]${white} Installing Ngrok..."
+        #if [[ $op == "y" ]];then
+            arch=$(uname -a | grep -o 'arm' | head -n1 )
+            arch2=$(uname -a | grep -o 'Android' | head -n1)
+            if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]];then
+                wget --no-check-certificate https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1
+
+                if [[ -e ngrok-stable-linux-arm.zip ]];then
+                    unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
+                    chmod +x ngrok
+                    rm -rf ngrok-stable-linux-arm.zip
+                else
+                    echo -e "${red}[-] Download error.. exiting...."
+                    sleep 2
+                    exit 1
+                fi
+            else
+            echo -e "${yellow}[+]${white} Installing Ngrok..."
+                wget --no-check-certificate https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
+                if [[ -e ngrok-stable-linux-386.zip ]];then
+                    unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
+                    chmod +x ngrok
+                    rm -rf ngrok-stable-linux-386.zip
+                else
+                    echo -e "${red}[-] Download error.. exiting...."
+                    sleep 2
+                    exit 1
+                fi
+            fi
+    fi
+
+if [[ -e ngrok ]];then
+	echo -e "${green}[+]${white} Moving ngrok to /usr/bin/ "
+	mv ngrok /usr/bin
+fi 
